Covo/urls.py
# """
# @Author: your name
# @Date: 2020-04-25 16:22:23
# @LastEditTime: 2020-06-02 23:29:11
# @LastEditors: FengSiJia
# @Description: In User Settings Edit
# @FilePath: \Covo\Covo\urls.py
# """
"""Covo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
# from django.views.static import serve
from . import views

app_name = 'Covo'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/user/', include('Users.urls')),
    path('api/v1/volunteer/', include('Volunteer.urls')),
    path('api/v1/recourse/', include('Recourse.urls')),
    path('api/v1/activity/', include('Activity.urls')),
    path('api/v1/applicationform/', include('ApplicationForm.urls')),
    path('api/v1/feedback/', include('Feedback.urls')),
    path('api/v1/walfare/', include('Walfare.urls')),
    path('api/v1/exchange/', include('Exchange.urls')),
    path('', TemplateView.as_view(template_name='index.html')),
    # path('api/users/', include('Users.urls')),
    path('index/', views.showIndex, name='index'),
    path('users/', include('Users.urls')),
    path('volunteer/', include('Volunteer.urls')),
    path('walfare/', include('Walfare.urls')),
    path('activity/', include('Activity.urls')),
    path('applicationform/', include('ApplicationForm.urls')),
    path('exchange/', include('Exchange.urls')),
    path('recourse/', include('Recourse.urls')),
    path('manager/', include('Manager.urls')),
    path('opinion/', include('Opinion.urls')),
    path('recruit/', include('Recruit.urls')),
]

Users/urls.py
# '''
# @Author: your name
# @Date: 2020-04-25 16:45:53
# @LastEditTime: 2020-06-02 23:27:03
# @LastEditors: FengSiJia
# @Description: In User Settings Edit
# @FilePath: \Covo\Users\urls.py
# '''
from django.urls import path,include
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from django.conf.urls import url

# router = DefaultRouter()
# router.register('userlist', views.UsersViewSet)
app_name='Users'
urlpatterns = [
    path('', views.User_List),
    path('<str:account>', views.User_Detail),
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),
    path('to_regist/', views.to_regist, name='to_regist'),
    path('regist/', views.regist, name='regist'),
    path('logout/', views.logout, name='logout'),
    path('userlist/', views.show_userlist),
    url(r'^api/v1/auth/$', views.AuthView.as_view()),
]
urlpatterns = format_suffix_patterns(urlpatterns)

Walfare/urls.py
'''
@Author: your name
@Date: 2020-04-25 16:53:37
@LastEditTime: 2020-05-12 02:20:53
@LastEditors: FengSiJia
@Description: In User Settings Edit
@FilePath: /Covo/Walfare/urls.py
'''
from django.urls import path
from .import views
from django.views.static import serve

app_name='Walfare'
urlpatterns = [
    path('imgurl/walfare/', views.imgUpload),
    path('', views.Walfare_List),
    path('<int:prize_number>', views.Walfare_Detail),
    path('<str:account>/<int:prize_number>', views.exchange_walfare),
    path('walfarelist/', views.get_walfarelist, name='walfarelist'),
    path('to_walfaremanager/', views.to_walfaremanager, name='to_walfaremanager'),
    path('add_walfare/', views.add_walfare, name='add_walfare'),
    path('save_walfare/', views.save_walfare, name='save_walfare'),
    path('edit_walfare/<int:prize_number>', views.edit_walfare, name='edit_walfare'),
    path('delete_walfare/<int:prize_number>', views.delete_walfare, name='delete_walfare'),
    path('exchange/<int:prize_number>', views.exchange, name='exchange'),
    # path('walfaremanager/', views.walfaremanager)
    path('walfareinfo/<int:prize_number>', views.get_walfareinfo, name='walfareinfo')
]

Walfare/models.py
'''
@Author: FengSiJia
@Date: 2020-04-25 16:42:26
@LastEditors: FengSiJia
@LastEditTime: 2020-04-25 20:45:06
@Description: file content
@FilePath: /Covo/Walfare/models.py
'''
from django.db import models

# Create your models here.
#志愿者福利管理 奖品编号（主码）、奖品名称、奖品积分、奖品简介、奖品图片
class Walfare(models.Model):
    prize_number = models.AutoField(primary_key=True)       # 奖品编号
    prize_name = models.CharField(max_length=40)            # 奖品名称
    prize_points = models.IntegerField(default=0)           # 奖品积分
    prize_introduction = models.TextField()                 # 奖品简介
    prize_image = models.CharField(max_length=200)          # 奖品图片

Walfare/views.py
'''
@Author: FengSiJia
@Date: 2020-04-25 16:42:26
@LastEditors: FengSiJia
@LastEditTime: 2020-05-12 02:32:31
@Description: file content
@FilePath: /Covo/Walfare/views.py
'''
'''
@Author: FengSiJia
@Date: 2020-04-25 16:42:26
@LastEditors: FengSiJia
@LastEditTime: 2020-05-01 00:50:42
@Description: file content
@FilePath: /Covo/Walfare/views.py
'''
import os
import time
from django.http import JsonResponse
from django.shortcuts import render,HttpResponse
from django.shortcuts import redirect
from .models import Walfare
from Users.models import Users
from Exchange.models import Exchange
from Volunteer.models import Volunteer
from Covo import settings
# Create your views here.
from .serializer import WalfareSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status

@api_view(['PUT'])
def exchange_walfare(request, account, prize_number):
    volunteer = Volunteer.objects.get(users = account)
    prize = Walfare.objects.get(prize_number = prize_number)
    volunteer.available_points -= prize.prize_points
    volunteer.save()
    user = Users.objects.get(account = account)

    Exchange.objects.create(account = user, voinfo = volunteer, prize_info = prize)
    return Response(status=status.HTTP_201_CREATED)
@api_view(['GET','POST'])
def Walfare_List(request, format=None):
    if request.method == 'GET':
        walfare = Walfare.objects.all()
        serializer = WalfareSerializer(walfare, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = WalfareSerializer(data=request.data)
        print(request.data)
        # print(serializer.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET', 'PUT', 'DELETE'])
def Walfare_Detail(request, prize_number):
    try:
        walfare = Walfare.objects.get(prize_number=prize_number)
        print("walfare")
    except Walfare.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    
    if request.method == 'GET':
        serializer = WalfareSerializer(walfare,many=True)
        return Response(serializer.data)

    elif request.method == 'PUT':
        print("put12312312312312321")
        serializer = WalfareSerializer(walfare, data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        walfare.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

def imgUpload(request):
    if(request.method == 'POST'):
        file_obj = request.FILES.get('walfareimg', None)
        print(file_obj)
        name = time.strftime("%Y%m%d%H%M%S", time.localtime()) + file_obj.name
        print(name)
        file_path = os.path.join(settings.UPLOAD_FILE, name)
        print(file_path)
        f = open(file_path,'wb')
        for i in file_obj.chunks():
            f.write(i)
        f.close()
        dict = {
            'msg': 'success',
            'img_path': name
        }
        print(file_obj.name)
        print(dict)
        return JsonResponse(dict)
        # return Response(status=status.HTTP_201_CREATED)
    

def get_walfarelist(request):
    context = {}
    context['account'] = request.session['account']
    context['is_manager'] = False
    context['av_points'] = request.session['av_points']
    context['ac_points'] = request.session['ac_points']
    context['walfarelist'] = Walfare.objects.all().values('prize_number','prize_name', 'prize_points')
    return render(request, './Walfare/walfarelist.html', context)

def to_walfaremanager(request):
    context = {}
    context['walfarelist'] = Walfare.objects.all().values('prize_number','prize_name', 'prize_points')
    # redirect('/Walfare/to_walfaremanager/')
    return render(request, './Walfare/walfaremanager.html', context)

def add_walfare(request):
    return render(request, './Walfare/add_walfare.html')

def save_walfare(request):
    if request.POST:
        if request.POST['prize_number'] is not 0:
            prize_name = request.POST['name']
            prize_introduction = request.POST['introduction']
            prize_points = request.POST['points']
            Walfare.objects.create(prize_name=prize_name, prize_introduction=prize_introduction, prize_points=prize_points)
        else:
            prize_number = request.POST['prize_number']
            walfare = Walfare.objects.get(prize_number=prize_number)
            walfare.prize_name = request.POST['name']
            walfare.prize_introduction = request.POST['introduction']
            walfare.prize_points = request.POST['points']
            walfare.save()
        # return to_walfaremanager(request)
        return redirect('/walfare/to_walfaremanager/')

def edit_walfare(request, prize_number):
    context = {}
    context['walfareinfo'] = Walfare.objects.get(prize_number=prize_number)
    return render(request, './Walfare/edit_walfare.html', context)

def delete_walfare(request, prize_number):
    Walfare.objects.get(prize_number=prize_number).delete()
    return to_walfaremanager(request)

def get_walfareinfo(request, prize_number):
    context = {}
    context['walfareinfo'] = Walfare.objects.get(prize_number=prize_number)
    return render(request, './Walfare/walfareinfo.html', context)


def exchange(request, prize_number):
    user = Users.objects.get(account = request.session['account'])
    vo_info = user.volunteer_set.all().get(users=user)
    prize = Walfare.objects.get(prize_number=prize_number)
    if vo_info.available_points < prize.prize_points:
        return HttpResponse('剩余积分不足，无法兑换！')
    vo_info.available_points -= prize.prize_points
    vo_info.save()
    request.session['av_points'] = vo_info.available_points
    return HttpResponse('兑换成功')

Walfare/templates/Walfare/add_walfare.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>志愿者福利管理</title>
</head>
<body>
    <h1>添加福利兑换奖品</h1>
    <form action="" id="add_walfare_form" method="POST">
    {% csrf_token %}
    奖品名称<br>
    <input type="text" name="name"><br>
    奖品简介<br>
    <textarea name="introduction"rows="20" cols="100">
    </textarea><br>
    兑换积分<br>
    <input type="text" name="points">
    </form>
</body>
</html>

Walfare/templates/Walfare/edit_walfare.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>志愿者福利管理</title>
</head>
<body>
    <h1>添加福利兑换奖品</h1>
    <form action="{% url 'Walfare:save_walfare'%}" id="add_walfare_form" method="POST">
    {% csrf_token %}
    <input type="text", name="prize_number" value="{{walfareinfo.prize_number}}" hidden="true">
    奖品名称<br>
    <input type="text" name="name" value="{{walfareinfo.prize_name}}"><br>
    奖品简介<br>
    <textarea name="introduction"rows="20" cols="100">
    {{walfareinfo.prize_introduction}}
    </textarea><br>
    兑换积分<br>
    <input type="text" name="points" value="{{walfareinfo.prize_points}}">
    <button form="add_walfare_form" type="submit">保存</button>
    </form>
</body>
</html>

Walfare/templates/Walfare/walfareinfo.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>福利奖品详细信息</title>
</head>
<body>
    <h1>福利奖品详细信息</h1>
    <table width="800" border="0">
        <tr>
            <td width="200">奖品编号</td>
            <td>{{ walfareinfo.prize_number}}</td>
        </tr>
        <tr>
            <td>奖品名称</td>
            <td>{{ walfareinfo.prize_name}}</td>
        </tr>
        <tr>
            <td>兑换积分</td>
            <td>{{ walfareinfo.prize_points}}</td>
        </tr>
        <tr>
            <td>奖品简介</td>
            <td>{{ walfareinfo.prize_introduction}}</td>
        </tr>
        <tr>
            <td>奖品图片</td>
            <td>{{ wakfareubfi.prize_image}}</td>
        </tr>
    </table>

</body>
</html>

Walfare/templates/Walfare/walfarelist.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>福利奖品列表</title>
</head>
<body>
    <h1>福利奖品列表</h1>
    <p>{% if is_manager %}您好，管理员{% else %} 您好，普通用户{% endif %}</p>
    <p>{% if not is_manager %} 当前积分:{{ac_points}}, 剩余积分:{{av_points}}{% endif%}</p>
    <table>
        <tr>
            <td>奖品编号</td>
            <td>奖品名称</td>
            <td>兑换积分</td>
            <td>操作</td>
        </tr>
        {% for walfare in walfarelist %}
        <tr>
            <td><a href="{% url 'Walfare:walfareinfo' walfare.prize_number%}"> {{ walfare.prize_number}}</a></td>
            <td><a href="{% url 'Walfare:walfareinfo' walfare.prize_number%}">{{ walfare.prize_name }}</a></td>
            <td><a href="{% url 'Walfare:walfareinfo' walfare.prize_number%}">{{walfare.prize_points}}</a></td>
            <td><a href="{% url 'Walfare:exchange' walfare.prize_number %}">兑换</a></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

Walfare/templates/Walfare/walfaremanager.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>福利奖品列表</title>
</head>
<body>
    <h1>志愿者福利管理</h1>
    <p><a href="{% url 'Users:index' %}">返回主页</a></p>
    <p><a href="{% url 'Walfare:add_walfare' %}">添加奖品</a></p>
    <table>
        <tr>
            <td>奖品编号</td>
            <td>奖品名称</td>
            <td>兑换积分</td>
            {% comment %} <td></td> {% endcomment %}
            <td>修改</td>
            <td>删除</td>
        </tr>
        {% for walfare in walfarelist %}
        <tr>
            <td><a href="{% url 'Walfare:walfareinfo' walfare.prize_number%}"> {{ walfare.prize_number}}</a></td>
            <td><a href="{% url 'Walfare:walfareinfo' walfare.prize_number%}">{{ walfare.prize_name }}</a></td>
            {% comment %} <td><a href="{% url 'Walfare:walfareinfo' walfare.prize_number%}">{{ walfare.prize_introduction }}</a></td> {% endcomment %}
            <td><a href="{% url 'Walfare:walfareinfo' walfare.prize_number%}">{{walfare.prize_points}}</a></td>
            <td><a href="{% url 'Walfare:edit_walfare' walfare.prize_number%}">修改</a></td>
            <td><a href="{% url 'Walfare:delete_walfare' walfare.prize_number%}">删除</a></td>
        </tr>
        {% endfor %}</a>
    </table>
</body>
</html>