Activity/urls.py
'''
@Author: your name
@Date: 2020-04-25 16:49:54
@LastEditTime: 2020-05-25 01:09:52
@LastEditors: FengSiJia
@Description: In User Settings Edit
@FilePath: /Covo/Activity/urls.py
'''
from django.urls import path
from . import views
from django.conf.urls import url
app_name='Activity'
urlpatterns = [
    path('', views.Activity_List),
    path('<int:activity_number>', views.Activity_Detail),
    path('to_recruit/', views.to_recruit, name='to_recruit'),
    path('recruit/', views.recruit, name='recruit'),
    path('activitylist/', views.activitylist, name='activitylist'),
    path('activityinfo/<int:activity_number>', views.show_activityinfo, name='activityinfo'),
    url(r'^activity/$', views.VolunteerList.as_view()),
    url(r'^activity/(?P<pk>[a-zA-Z0-9]{1,})/$', views.VolunteerDetail.as_view()),
]

Covo/urls.py
# """
# @Author: your name
# @Date: 2020-04-25 16:22:23
# @LastEditTime: 2020-06-02 23:29:11
# @LastEditors: FengSiJia
# @Description: In User Settings Edit
# @FilePath: \Covo\Covo\urls.py
# """
"""Covo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
# from django.views.static import serve
from . import views

app_name = 'Covo'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/user/', include('Users.urls')),
    path('api/v1/volunteer/', include('Volunteer.urls')),
    path('api/v1/recourse/', include('Recourse.urls')),
    path('api/v1/activity/', include('Activity.urls')),
    path('api/v1/applicationform/', include('ApplicationForm.urls')),
    path('api/v1/feedback/', include('Feedback.urls')),
    path('api/v1/walfare/', include('Walfare.urls')),
    path('api/v1/exchange/', include('Exchange.urls')),
    path('', TemplateView.as_view(template_name='index.html')),
    # path('api/users/', include('Users.urls')),
    path('index/', views.showIndex, name='index'),
    path('users/', include('Users.urls')),
    path('volunteer/', include('Volunteer.urls')),
    path('walfare/', include('Walfare.urls')),
    path('activity/', include('Activity.urls')),
    path('applicationform/', include('ApplicationForm.urls')),
    path('exchange/', include('Exchange.urls')),
    path('recourse/', include('Recourse.urls')),
    path('manager/', include('Manager.urls')),
    path('opinion/', include('Opinion.urls')),
    path('recruit/', include('Recruit.urls')),
]

Activity/models.py
'''
@Author: your name
@Date: 2020-04-25 16:41:21
@LastEditTime: 2020-05-04 23:26:10
@LastEditors: FengSiJia
@Description: In User Settings Edit
@FilePath: /Covo/Activity/models.py
'''
from django.db import models

# Create your models here.
# 志愿者活动信息管理 活动编号、活动名称、活动简介、活动是否过期、活动所需人数、参加人数、活动所在地、活动积分、联系人
class Activity(models.Model):
    activity_number = models.AutoField(primary_key=True)    # 活动编号
    activity_name = models.CharField(max_length=20)         # 活动名称
    introduction = models.TextField()                       # 活动简介
    expired = models.IntegerField(default=0)                # 是否过期
    required_num = models.IntegerField(default=0)           # 所需人数
    participants = models.IntegerField(default=0)           # 参加人数
    address = models.CharField(max_length=40)               # 活动所在地
    activity_points = models.IntegerField(default=0)        # 活动积分
    date = models.DateTimeField()                           # 活动时间
    contact = models.CharField(max_length=20)               # 联系人

    def __str__(self):
        return str(self.activity_number)

Activity/views.py
'''
@Author: your name
@Date: 2020-04-25 16:41:21
@LastEditTime: 2020-05-25 01:09:12
@LastEditors: FengSiJia
@Description: In User Settings Edit
@FilePath: /Covo/Activity/views.py
'''
from django.shortcuts import render
from .models import Activity
from .serializers import ActivitySerializer
# from rest_framework import request
from rest_framework.response import Response
from rest_framework.views import APIView
from django.http import Http404
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status

from Volunteer.models import Volunteer
from ApplicationForm.models import Apply
# Create your views here.

@api_view(['GET','POST'])
def Activity_List(request, format=None):
    if request.method == 'GET':
        activity = Activity.objects.all()
        serializer = ActivitySerializer(activity, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = ActivitySerializer(data=request.data)
        print(request.data)
        # print(serializer.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET', 'PUT', 'DELETE'])
def Activity_Detail(request, activity_number):
    try:
        activity = Activity.objects.get(activity_number=activity_number)
    except Activity.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    
    if request.method == 'GET':
        serializer = ActivitySerializer(activity)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = ActivitySerializer(activity, data = request.data)
        if serializer.is_valid():
            serializer.save()
            if (activity.expired == 2):
                calPoint(activity.activity_number)

            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        activity.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

def calPoint(activity_number):
    activity = Activity.objects.get(activity_number = activity_number)
    apply_set = Apply.objects.filter(activity_number = activity_number, status=1)
    for app in apply_set:
        print(app.account)
        voInfo = app.voinfo
        print(voInfo.activity_points)
        voInfo.activity_points += activity.activity_points
        voInfo.available_points += activity.activity_points
        voInfo.save()
    # voInfo_set = Volunteer.objects.filter(activity_)
class VolunteerList(APIView):
    def get(self, request, format=None):
        activity = Activity.objects.all()
        serializer = ActivitySerializer(activity, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = ActivitySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class VolunteerDetail(APIView):
    def get_object(self, pk):
        try:
            return Activity.objects.get(users=pk)
        except Activity.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        activity = self.get_object(pk)
        serializer = ActivitySerializer(activity)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        activity = self.get_object(pk)
        serializer = ActivitySerializer(activity, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        activity = self.get_object(pk)
        activity.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

def to_recruit(request):
    return render(request, './Activity/to_recruit.html')
    
def recruit(request):
    if request.POST:
        name = request.POST['name']
        introduction = request.POST['introduction']
        required = request.POST['required']
        address = request.POST['address']
        contact = request.POST['contact']
        date = request.POST['date']
        date = date.replace('T', ' ')
        print(date)
        points = request.POST['points']
        # Recourse.objects.create(title=title, text=text, users=users)
        Activity.objects.create(activity_name=name, introduction=introduction, required_num=required, address=address, date=date, activity_points=points, contact=contact)
    return render(request, './Users/userIndex.html',{'account': request.session['account'],'is_login': request.session['is_login'], 'is_manager': request.session['is_manager']})

def activitylist(request):
    context = {}
    context['activitylist'] = Activity.objects.all().values('activity_number', 'activity_name', 'date')
    context['is_manager'] = request.session['is_manager']
    return render(request, './Activity/activitylist.html', context)

def show_activityinfo(request, activity_number):
    context = {}
    context['activityinfo'] = Activity.objects.get(activity_number=activity_number)
    return render(request, './Activity/activityinfo.html', context)

Activity/templates/Activity/activityinfo.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>志愿者活动详细信息</title>
</head>
<body>
    <h1>志愿者活动详细信息</h1>
    <table width="800" border="0">
        <tr>
            <td width="200">活动编号</td>
            <td>{{ activityinfo.activity_number}}</td>
        </tr>
        <tr>
            <td>活动名称</td>
            <td>{{ activityinfo.activity_name}}</td>
        </tr>
        <tr>
            <td>活动简介</td>
            <td>{{ activityinfo.introduction}}</td>
        </tr>
        <tr>
            <td>是否过期</td>
            <td>{{ activityinfo.expired}}</td>
        </tr>
        <tr>
            <td>活动所需人数</td>
            <td>{{ activityinfo.required_num}}</td>
        </tr>
        <tr>
            <td>参加人数</td>
            <td>{{ activityinfo.participants}}</td>
        </tr>
        <tr>
            <td>活动所在地</td>
            <td>{{ activityinfo.address}}</td>
        </tr>
        <tr>
            <td>活动积分</td>
            <td>{{ activityinfo.activity_points}}</td>
        </tr>
        <tr>
            <td>联系人</td>
            <td>{{ activityinfo.contact}}</td>
        </tr>
    </table>
    <a href=""><button>参加</button></a>

</body>
</html>

Activity/templates/Activity/activitylist.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>志愿者活动列表</title>
</head>
<body>
    <h1>志愿者活动列表</h1>
    <table>
        <tr>
            <td>活动编号</td>
            <td>活动名称</td>
            <td>活动时间</td>
            {% if not is_manager %}<td>操作</td>{% endif %}
        </tr>
        {% for activity in activitylist %}
        <tr>
            <td><a href="{% url 'Activity:activityinfo' activity.activity_number%}">{{ activity.activity_number}}</a></td>
            <td><a href="{% url 'Activity:activityinfo' activity.activity_number%}">{{ activity.activity_name }}</a></td>
            <td>{{ activity.date|date:"Y-m-d H:i:s"}}</td>
            {% if not is_manager %} <td><a href="{% url 'ApplicationForm:apply' activity.activity_number%}">报名</a></td>{% endif %}
        </tr>
        {% endfor %}
    <table>
</body>
</html>

Activity/templates/Activity/to_recruit.html
<!DOCTYPE html>
<html>
<style type="text/css">
        html, body {
            height: 100%;
            overflow: auto;
        }
        body {
            padding: 0;
            margin: 0;
        }
    </style>
<head>
<meta charset="utf-8">
<title>志愿者活动发布</title>
</head>
<body>
    <h1 align="center" valign="middle">志愿者活动发布</h1>
    <h2>{{error}}</h2>
    <form style="height:100%;"align="center" valign="middle" action="{% url 'Activity:recruit' %}" method="POST" id="recruit_form">
    {% csrf_token %}
    活动名称:<br>
    <input type="text" name="name">
    <br>
    活动简介<br>
    <textarea name="introduction"" rows="20" cols="100"></textarea>
    <br>
    所需人数<br>
    <input type="text" name="required">
    <br>
    活动所在地<br>
    <input type="text" name="address">
    <br>
    活动积分<br>
    <input type="text" name="points">
    <br>
    活动时间<br>
    <input type="datetime-local" name="date" />
    <br>
    联系人<br>
    <input type="text" name="contact">
    <br>
    <button form="recruit_form" type="submit" name="">发布</button>
    
    </form>
</body>
</html>