Covo/urls.py
# """
# @Author: your name
# @Date: 2020-04-25 16:22:23
# @LastEditTime: 2020-06-02 23:29:11
# @LastEditors: FengSiJia
# @Description: In User Settings Edit
# @FilePath: \Covo\Covo\urls.py
# """
"""Covo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
# from django.views.static import serve
from . import views

app_name = 'Covo'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/user/', include('Users.urls')),
    path('api/v1/volunteer/', include('Volunteer.urls')),
    path('api/v1/recourse/', include('Recourse.urls')),
    path('api/v1/activity/', include('Activity.urls')),
    path('api/v1/applicationform/', include('ApplicationForm.urls')),
    path('api/v1/feedback/', include('Feedback.urls')),
    path('api/v1/walfare/', include('Walfare.urls')),
    path('api/v1/exchange/', include('Exchange.urls')),
    path('', TemplateView.as_view(template_name='index.html')),
    # path('api/users/', include('Users.urls')),
    path('index/', views.showIndex, name='index'),
    path('users/', include('Users.urls')),
    path('volunteer/', include('Volunteer.urls')),
    path('walfare/', include('Walfare.urls')),
    path('activity/', include('Activity.urls')),
    path('applicationform/', include('ApplicationForm.urls')),
    path('exchange/', include('Exchange.urls')),
    path('recourse/', include('Recourse.urls')),
    path('manager/', include('Manager.urls')),
    path('opinion/', include('Opinion.urls')),
    path('recruit/', include('Recruit.urls')),
]

Users/urls.py
# '''
# @Author: your name
# @Date: 2020-04-25 16:45:53
# @LastEditTime: 2020-06-02 23:27:03
# @LastEditors: FengSiJia
# @Description: In User Settings Edit
# @FilePath: \Covo\Users\urls.py
# '''
from django.urls import path,include
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from django.conf.urls import url

# router = DefaultRouter()
# router.register('userlist', views.UsersViewSet)
app_name='Users'
urlpatterns = [
    path('', views.User_List),
    path('<str:account>', views.User_Detail),
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),
    path('to_regist/', views.to_regist, name='to_regist'),
    path('regist/', views.regist, name='regist'),
    path('logout/', views.logout, name='logout'),
    path('userlist/', views.show_userlist),
    url(r'^api/v1/auth/$', views.AuthView.as_view()),
]
urlpatterns = format_suffix_patterns(urlpatterns)

Covo/views.py
'''
@Author: FengSiJia
@Date: 2020-04-26 21:42:13
@LastEditors: FengSiJia
@LastEditTime: 2020-04-26 21:50:36
@Description: file content
@FilePath: /Covo/Covo/views.py
'''

from django.shortcuts import render

def showIndex(request):
    return render(request, './Covo/index.html')

Covo/templates/Covo/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>志愿活动管理系统</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Covo/index.css' %}">
</head>
<body>
    {% comment %} <div id="wrapper">
        <div class="dv1"><span id="sp1">登录</span></div>

    <div class='input' contenteditable placeholder='请输入文字'></div>

    </div> {% endcomment %}
    <h1 align="center" valign="middle">志愿活动管理系统</h1>
    <h2>{{error}}</h2>
    <form style="height:100%;"align="center" valign="middle" action="{% url 'Users:login' %}" method="POST" id="regist_form">
    {% csrf_token %}
    账户:<br>
    <input type="text" name="account">
    <br>
    密码：<br>
    <input type="password" name="password">
    <br>
    <button form="regist_form" type="submit" name="">登录</button>
    {% comment %} <a href="{% url 'Users:to_regist'%}">注册</a>  {% endcomment %}
    <button type="button"><a href="{% url 'Users:to_regist'%}">注册</a></button>
    </form> 
</body>
</html>