Activity/urls.py
'''
@Author: your name
@Date: 2020-04-25 16:49:54
@LastEditTime: 2020-05-25 01:09:52
@LastEditors: FengSiJia
@Description: In User Settings Edit
@FilePath: /Covo/Activity/urls.py
'''
from django.urls import path
from . import views
from django.conf.urls import url
app_name='Activity'
urlpatterns = [
    path('', views.Activity_List),
    path('<int:activity_number>', views.Activity_Detail),
    path('to_recruit/', views.to_recruit, name='to_recruit'),
    path('recruit/', views.recruit, name='recruit'),
    path('activitylist/', views.activitylist, name='activitylist'),
    path('activityinfo/<int:activity_number>', views.show_activityinfo, name='activityinfo'),
    url(r'^activity/$', views.VolunteerList.as_view()),
    url(r'^activity/(?P<pk>[a-zA-Z0-9]{1,})/$', views.VolunteerDetail.as_view()),
]

Covo/urls.py
# """
# @Author: your name
# @Date: 2020-04-25 16:22:23
# @LastEditTime: 2020-06-02 23:29:11
# @LastEditors: FengSiJia
# @Description: In User Settings Edit
# @FilePath: \Covo\Covo\urls.py
# """
"""Covo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
# from django.views.static import serve
from . import views

app_name = 'Covo'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/user/', include('Users.urls')),
    path('api/v1/volunteer/', include('Volunteer.urls')),
    path('api/v1/recourse/', include('Recourse.urls')),
    path('api/v1/activity/', include('Activity.urls')),
    path('api/v1/applicationform/', include('ApplicationForm.urls')),
    path('api/v1/feedback/', include('Feedback.urls')),
    path('api/v1/walfare/', include('Walfare.urls')),
    path('api/v1/exchange/', include('Exchange.urls')),
    path('', TemplateView.as_view(template_name='index.html')),
    # path('api/users/', include('Users.urls')),
    path('index/', views.showIndex, name='index'),
    path('users/', include('Users.urls')),
    path('volunteer/', include('Volunteer.urls')),
    path('walfare/', include('Walfare.urls')),
    path('activity/', include('Activity.urls')),
    path('applicationform/', include('ApplicationForm.urls')),
    path('exchange/', include('Exchange.urls')),
    path('recourse/', include('Recourse.urls')),
    path('manager/', include('Manager.urls')),
    path('opinion/', include('Opinion.urls')),
    path('recruit/', include('Recruit.urls')),
]

Recourse/urls.py
from django.urls import path
from . import views

app_name='Recourse'
urlpatterns = [
    path('', views.Recourse_List),
    path('<int:index>', views.Recourse_Detail),
    path('<str:account>', views.MyRecourse_List),
    path('to_recourse/', views.to_recourse, name='to_recourse'),
    path('record_recourse/', views.record_recourse, name='record_recourse'),
    path('show_list/', views.show_list, name='show_list'),
    # path('helperlist/', views.get_helperlist),
    # path('helperinfo/<int:helper_number>', views.get_helperinfo, name='helperinfo'),
]

Recourse/models.py
'''
@Author: FengSiJia
@Date: 2020-04-25 16:41:48
@LastEditors: FengSiJia
@LastEditTime: 2020-06-06 02:15:17
@Description: file content
@FilePath: \Covo\Recourse\models.py
'''
from django.db import models

# Create your models here.
# 求助事件
class Recourse(models.Model):
    index = models.AutoField(primary_key=True)      # 求助编号
    title = models.CharField(max_length=20)         # 求助标题
    text = models.TextField()                       # 求助内容
    time = models.DateTimeField(auto_now_add=True)  # 求助时间
    status = models.IntegerField(default=0)         # 求助状态   0: 求助中  1: 已完成  2: 已拒绝
    activity_num = models.IntegerField(default=-1)  # 活动编号
    users = models.ForeignKey('Users.Users', on_delete=models.CASCADE)              # 用户名

Recourse/views.py
'''
@Author: FengSiJia
@Date: 2020-04-25 16:41:48
@LastEditors: FengSiJia
@LastEditTime: 2020-06-06 02:18:23
@Description: file content
@FilePath: \Covo\Recourse\views.py
'''
'''
@Author: FengSiJia
'''
from django.shortcuts import render
from .models import Recourse
from Users.models import Users
from .serializer import RecourseSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
# Create your views here.

@api_view(['GET','POST'])
def Recourse_List(request, format=None):
    if request.method == 'GET':
        recourese = Recourse.objects.all()
        serializer = RecourseSerializer(recourese, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = RecourseSerializer(data=request.data)
        print(request.data)
        # print(serializer.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET', 'PUT', 'DELETE'])
def Recourse_Detail(request, index):
    try:
        recourese = Recourse.objects.get(index=index)
    except Recourse.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    
    if request.method == 'GET':
        serializer = RecourseSerializer(recourese)
        return Response(serializer.data)

    elif request.method == 'PUT':
        print("put12312312312312321")
        serializer = RecourseSerializer(recourese, data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        recourese.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

@api_view(['GET','POST'])
def MyRecourse_List(request, account, format=None):
    if request.method == 'GET':
        recourese = Recourse.objects.filter(users=account)
        serializer = RecourseSerializer(recourese, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = RecourseSerializer(data=request.data)
        print(request.data)
        # print(serializer.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET', 'PUT', 'DELETE'])
def MyRecourse_Detail(request, account):
    try:
        recourese = Recourse.objects.get(users=account)
    except Recourse.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    
    if request.method == 'GET':
        serializer = RecourseSerializer(recourese)
        return Response(serializer.data)

    elif request.method == 'PUT':
        print("put12312312312312321")
        serializer = RecourseSerializer(recourese, data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        recourese.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


def to_recourse(request):
    return render(request, './Recourse/recourse.html')

def record_recourse(request):
    if request.POST:
        title = request.POST['title']
        text = request.POST['text']
        account = request.session['account']
        users = Users.objects.get(account=account)
        Recourse.objects.create(title=title, text=text, users=users)
        return render(request, './Users/userIndex.html', {'account': account, 'is_manager': users.manager})
    return render(request, './Recourse/recourse.html', {'error': '发布失败'})

def show_list(request):
    context = {}
    context['recourse_list'] = Recourse.objects.all().values('index','title', 'time', 'users')
    print(context['recourse_list'])
    return render(request, './Recourse/show_list.html', context)
# def get_helperlist(request):
#     context = {}
#     context['helperlist'] = Recourse.objects.all().values('helper_number', 'helper_name')
#     return render(request, './Helper/helperlist.html', context)

# def get_helperinfo(request, helper_number):
#     context = {}
#     context['helperinfo'] = Recourse.objects.get(helper_number = helper_number)
#     return render(request, './Helper/helperinfo.html', context)

Recourse/templates/Recourse/helperinfo.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>求助者详细信息</title>
</head>
<body>
    <h1>求助者详细信息</h1>
    <table width="800" border="0">
        <tr>
            <td width="200">求助者编号</td>
            <td>{{ helperinfo.helper_number}}</td>
        </tr>
        <tr>
            <td>求助者姓名</td>
            <td>{{ helperinfo.helper_name}}</td>
        </tr>
        <tr>
            <td>手机号</td>
            <td>{{ helperinfo.helper_tel}}</td>
        </tr>
        <tr>
            <td>地址</td>
            <td>{{ helperinfo.helper_address}}</td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>{{ helperinfo.account}}</td>
        </tr>
    </table>

</body>
</html>

Recourse/templates/Recourse/helperlist.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>求助者列表</title>
</head>
<body>
    <h1>求助者列表</h1>
    <p>求助者编号  求助者姓名</p>
    {% comment %} {% for activity in activitylist %}
    <li> <a href="{% url 'Activity:activityinfo' activity.activity_number%}">{{ activity.activity_number}} {{ activity.activity_name }} </li>
    {% endfor %}</a> {% endcomment %}
    {% for helper in helperlist %}
    <li><a href="{% url 'Helper:helperinfo' helper.helper_number %}"">{{ helper.helper_number}} {{helper.helper_name}}</a></li>
    {% endfor %}
</body>
</html>

Recourse/templates/Recourse/recourse.html
<!DOCTYPE html>
<html>
<style type="text/css">
        html, body {
            height: 100%;
            overflow: auto;
        }
        body {
            padding: 0;
            margin: 0;
        }
    </style>
<head>
<meta charset="utf-8">
<title>发布求助信息</title>
</head>
<body>
    <h1 align="center" valign="middle">发布求助信息</h1>
    <form style="height:100%;"align="center" valign="middle" action="{% url 'Recourse:record_recourse'%}" method="POST" id="recourse_form">
    {% csrf_token %}
    求助标题:<br>
    <input type="text" name="title" style="width:615px;">
    <br>
    求助内容<br>
    <textarea name="text"" rows="20" cols="100">
    </textarea>
    <br>
    <button form="recourse_form" type="submit" name="">提交</button>
    </form>
</body>
</html>

Recourse/templates/Recourse/show_list.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>求助信息列表</title>
</head>
<body>
    <h1>求助信息列表</h1>
    <table>
        <tr>
            <td>求助活动编号</td>
            <td>求助活动标题</td>
            <td>求助者时间</td>
            <td>活动状态</td>
        </tr>
        {% for recourse in recourse_list %}
        <tr>
            <td>{{recourse.index}}</td>
            <td>{{recourse.title}}</td>
            <td>{{recourse.time}}</td>
            <td><button>求助中</button></td>
        </td>
        {% endfor %}
    </table>
    {% comment %} {% for activity in activitylist %}
    <li> <a href="{% url 'Activity:activityinfo' activity.activity_number%}">{{ activity.activity_number}} {{ activity.activity_name }} </li>
    {% endfor %}</a> {% endcomment %}
</body>
</html>